redis:
  image: redis

db:
  image: postgres:9.4
  environment:
    - POSTGRES_HOST_AUTH_METHOD=trust

vote:
  image: voting-app
  links:
    - redis
  ports:
    - 5000:80

result:
  image: result-app
  links:
    - db
  ports:
    - 5001:80

worker: 
  image: worker
  links:
    - redis
    - db